worker_processes auto;

events {
    worker_connections 4096;
    multi_accept on;
}

http {

    keepalive_timeout 65;
    keepalive_requests 10000;

    upstream creation_service_cluster {
        server url_creation_service_a:8000;
        server url_creation_service_b:8000;
        server url_creation_service_c:8000;
        server url_creation_service_d:8000;
    }

    upstream redirect_service_cluster {
        server url_redirect_service:8000;
    }

    server {
        listen 80;

        location /create/ {
            proxy_pass http://creation_service_cluster/;
        }

        location / {
            proxy_pass http://redirect_service_cluster/;
        }
    }
}