events {}

http {

    upstream creation_service_cluster {
        server url_creation_service_a:8000;
        server url_creation_service_b:8000;
        server url_creation_service_c:8000;
        server url_creation_service_d:8000;
    }

    upstream redirect_service_cluster {
        server url_redirect_service:8000;
    }

    server {
        listen 80;

        

        # /create/... -> /... on creation service
        location /create/ {
            proxy_pass http://creation_service_cluster/;
        }

        # everything else -> redirect service
        location / {
            proxy_pass http://redirect_service_cluster;
        }
    }
}